### PR TITLE
Fix pmcjoder issues

### LINKED ISSUE #93: Pmcjoder issues
- [x] GPS location of the weather station is wrong
- [x] Missing humidity values

### PR DESCRIPTION
**Pull request by MichalBryxi**
1. Add humidity value to Neuhuus weather station
2. Fix of Neuhuus weather station GPS location
    - I managed to copy&paste coordinates for wrong weather station when copying from https://enwebs.ch/thunersee/
    - Fixed and visually verified with actual maps that the coordinates are correct

- Fixes #93

### CODE REVIEW

**Comment by MichalBryxi** [comment]
Screenshot 2024-06-30 at 18 55 16

Humidity seems to be collected ok.

**Comment by MichalBryxi** [comment]
The position of the weather station according to their website:

Screenshot 2024-06-30 at 18 26 59

My manual check verifying that new GPS position is correct:

Screenshot 2024-06-30 at 18 27 08

**Review by ysavary — APPROVED** [review]
Great, let's deploy your fixes!

**Comment by MichalBryxi** [comment]
Also @ysavary : I just updated a property on existing weather station. Would that update that in the db? Or would we need to wipe it out from the db first?

**Pull request merged**
